/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Practicas;

import javax.swing.JOptionPane;

/**
 *
 * @author arrivera
 */
public class DialogNuevoModificar extends javax.swing.JDialog {

    /**
     * Creates new form DialogNuevoModificar
     */
    boolean modificacionModal;
    public DialogNuevoModificar(java.awt.Frame parent, boolean modal, boolean modificacion) {
        super(parent, modal);
        initComponents();
        if(modificacion)
            btnNuevo.setText("Actualizar");
        else
            btnNuevo.setText("Nuevo");
        
        modificacionModal = modificacion;
    }

    public String GetProducto(){
        return cbProductos.getSelectedItem().toString();
    }
    public String GetCantidad(){
        return txtCantidad.getText();
    }
    public String GetPrecio(){
        return txtPrecio.getText();
    }
    
    public void setProducto(String producto){
        cbProductos.setSelectedItem(producto);
    }
    
    public void setCantidad(String cantidad){
        txtCantidad.setText(cantidad);
    }
    
    public void setPrecio(String precio){
        txtPrecio.setText(precio);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlbProducto = new javax.swing.JLabel();
        jlbCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jlbPrecio = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        cbProductos = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Administración Productos");

        jlbProducto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbProducto.setText("Producto");

        jlbCantidad.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbCantidad.setText("Cantidad");

        txtCantidad.setText("0");

        jlbPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jlbPrecio.setText("Precio");

        txtPrecio.setText("0");

        btnNuevo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        cbProductos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione un producto...", "Pollo Lb", "Res Lb", "Tajo Lb", "Aguacate Unidad", "Frijoles Lb", "Sal bolsa", "Huevo Unidad", "HotDog Unidad", "Mortadela", "Maseca" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jlbPrecio)
                            .addComponent(jlbCantidad)
                            .addComponent(jlbProducto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidad, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cbProductos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 16, Short.MAX_VALUE)
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jlbProducto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(cbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbCantidad)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlbPrecio)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        //Notificar al padre que se cerro la operación
        this.setRootPane(null); //Esto destruye los elementos de la interfaz
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        int productoindex = cbProductos.getSelectedIndex();
        double cantidad,precio;
        try{
            cantidad = Double.parseDouble(txtCantidad.getText());
            precio = Double.parseDouble(txtPrecio.getText());
        }catch (NumberFormatException ex){
                JOptionPane.showMessageDialog(this, "El precio o cantidad deben ser numero","Datos incorrectos",JOptionPane.WARNING_MESSAGE);
                return;
        }
        
        if(productoindex == 0){
                JOptionPane.showMessageDialog(this, "El nombre del prducto no puede ser vacio","Producto incorrecto",JOptionPane.WARNING_MESSAGE);
                return;
            }
            if (cantidad <= 0) {
                JOptionPane.showMessageDialog(this, "La cantidad debe ser mayor a cero","Cantidad incorrecta",JOptionPane.WARNING_MESSAGE);
                return;
            }
             if (precio <= 0) {
                JOptionPane.showMessageDialog(this, "El precio debe ser mayor a cero","Precio incorrecto",JOptionPane.WARNING_MESSAGE);
                return;
            }

            //CONFIRMAR QUE DESEA GUARDAR
            String mensaje;
            if(modificacionModal)
                mensaje = "¿Quieres actualizar este producto?";
            else
                mensaje = "¿Quieres agregar este producto?";
            int respuesta = JOptionPane.showConfirmDialog(this, mensaje);
            System.out.println(respuesta);
            
            //NOTIFICAR AL PADRE LO QUE SE QUIERE HACER
            if(respuesta == 0){
                this.setVisible(false);
                
            }
    }//GEN-LAST:event_btnNuevoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogNuevoModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogNuevoModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogNuevoModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogNuevoModificar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogNuevoModificar dialog = new DialogNuevoModificar(new javax.swing.JFrame(), true, false);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JComboBox<String> cbProductos;
    private javax.swing.JLabel jlbCantidad;
    private javax.swing.JLabel jlbPrecio;
    private javax.swing.JLabel jlbProducto;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
